name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign NEW issues and NEW pull requests to project 5
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'java-fundamentals')
        with:
          project: 'https://github.com/bobocode-projects/java-fundamentals-course/projects/4'
